# Generated by Django 5.2.7 on 2025-10-26 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('region', models.CharField(help_text='Affected region', max_length=200)),
                ('related_cause', models.CharField(choices=[('air_pollution', 'Air Pollution'), ('water_contamination', 'Contaminated Water'), ('heatwave', 'Extreme Heat/Heatwave'), ('flooding', 'Flooding'), ('drought', 'Drought'), ('poor_sanitation', 'Poor Sanitation'), ('waste_pollution', 'Waste Pollution'), ('climate_stress', 'General Climate Stress'), ('unknown', 'Unknown')], max_length=50)),
                ('preventive_measures', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Health Advisories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(choices=[('respiratory', 'Respiratory Issues'), ('waterborne', 'Waterborne Diseases'), ('vector', 'Vector-borne Diseases'), ('heat_related', 'Heat-related Illness'), ('skin', 'Skin Conditions'), ('cardiovascular', 'Cardiovascular Issues'), ('mental_health', 'Mental Health Issues'), ('other', 'Other')], max_length=50)),
                ('symptoms', models.TextField(help_text='Describe the symptoms experienced')),
                ('environmental_cause', models.CharField(choices=[('air_pollution', 'Air Pollution'), ('water_contamination', 'Contaminated Water'), ('heatwave', 'Extreme Heat/Heatwave'), ('flooding', 'Flooding'), ('drought', 'Drought'), ('poor_sanitation', 'Poor Sanitation'), ('waste_pollution', 'Waste Pollution'), ('climate_stress', 'General Climate Stress'), ('unknown', 'Unknown')], max_length=50)),
                ('location', models.CharField(help_text='City, District, or specific area', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('affected_count', models.IntegerField(default=1, help_text='Number of people affected')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from health officials')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_update', 'Report Status Update'), ('advisory', 'Health Advisory'), ('response', 'Admin Response')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_reports.healthreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Public User'), ('admin', 'Health Official/Admin')], default='user', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='healthreport',
            index=models.Index(fields=['status', 'created_at'], name='health_repo_status_ea74b9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthreport',
            index=models.Index(fields=['disease_type'], name='health_repo_disease_aedd60_idx'),
        ),
        migrations.AddIndex(
            model_name='healthreport',
            index=models.Index(fields=['environmental_cause'], name='health_repo_environ_8991ba_idx'),
        ),
    ]
